spring.datasource.url=jdbc:${DATABASE_URL}
spring.datasource.username=${PGUSER}
spring.datasource.password=${PGPASSWORD}

spring.sql.init.mode=never

#postgresql://postgres:BaBzSFCcLnjbJtRYhburxzXQWvdBALPN@postgres.railway.internal:5432/railway